export const companyTypes = [
  "Tech",
  "FinTech",
  "Banking",
  "E-commerce",
  "Consulting",
  "Telecom",
  "Manufacturing",
  "Semiconductor",
  "Automotive",
  "Logistics",
  "Energy",
  "Chemical",
  "Construction",
  "Mining",
  "Healthcare",
  "Real Estate",
  "Aviation",
  "Research",
  "Education",
  "Entertainment",
  "Startups",
];
