
export const departments = [
  "Computer Engineering",
  "Electrical Engineering",
  "Mechanical Engineering",
  "Civil Engineering",
  "Industrial Engineering",
  "Chemical Engineering",
  "Environmental Engineering",
  "Survey Engineering",
  "Mining and Petroleum Engineering",
  "Nuclear Engineering",
  "Aerospace Engineering",
  "Metallurgical and Materials Engineering",
  "Water Resources Engineering",
  "Information and Communication Engineering",
  "Nano-Engineering",
  "Automotive Design and Manufacturing Engineering",
  "Robotics and AI Engineering",
  "International School of Engineering (ISE)",
];
