export type Score = 1 | 2 | 3 | 4 | 5;

export type Company = {
  id: string;
  name: string;
  tag: string;
  rating: number;
  reviewCount: number;
  recommendCount: number;
  scores: {
    work: number;
    social: number;
    mentor: number;
    experience: number;
  };
};

export type Review = {
  id: string;
  companyId: string;
  name: string;
  department: string;
  intania: string;
  daysAgo: number;
  recommended: boolean;
  position: string;
  duration: string;
  compensation: string;
  workMode: string;
  openYears: string;
  minGpa: number | null;
  scores: {
    work: Score;
    social: Score;
    mentor: Score;
    experience: Score;
  };
  sections: {
    application: string;
    work: string;
    atmosphere: string;
    welfare?: string;
    advice: string;
  };
};

export const companies: Company[] = [
  {
    id: "line-man-wongnai",
    name: "LINE MAN Wongnai",
    tag: "Tech",
    rating: 4.6,
    reviewCount: 21,
    recommendCount: 18,
    scores: { work: 4.6, social: 4.4, mentor: 4.6, experience: 4.8 },
  },
  {
    id: "agoda",
    name: "Agoda",
    tag: "Travel",
    rating: 4.4,
    reviewCount: 16,
    recommendCount: 13,
    scores: { work: 4.7, social: 4.3, mentor: 4.2, experience: 4.8 },
  },
  {
    id: "scb-techx",
    name: "SCB TechX",
    tag: "FinTech",
    rating: 4.3,
    reviewCount: 19,
    recommendCount: 11,
    scores: { work: 4.2, social: 4.1, mentor: 3.9, experience: 4.5 },
  },
  {
    id: "shopee",
    name: "Shopee",
    tag: "E-com",
    rating: 4.5,
    reviewCount: 18,
    recommendCount: 14,
    scores: { work: 4.7, social: 4.2, mentor: 4.3, experience: 4.6 },
  },
  {
    id: "scg",
    name: "SCG",
    tag: "Manufacturing",
    rating: 4.2,
    reviewCount: 15,
    recommendCount: 11,
    scores: { work: 4.1, social: 4.3, mentor: 4.2, experience: 4.2 },
  },
  {
    id: "ptt",
    name: "PTT",
    tag: "Energy",
    rating: 4.1,
    reviewCount: 17,
    recommendCount: 10,
    scores: { work: 4.0, social: 4.2, mentor: 4.1, experience: 4.2 },
  },
  {
    id: "ey",
    name: "EY",
    tag: "Consulting",
    rating: 4.0,
    reviewCount: 12,
    recommendCount: 8,
    scores: { work: 4.2, social: 3.9, mentor: 3.8, experience: 4.1 },
  },
  {
    id: "ais",
    name: "AIS",
    tag: "Telecom",
    rating: 4.2,
    reviewCount: 14,
    recommendCount: 10,
    scores: { work: 4.1, social: 4.2, mentor: 4.2, experience: 4.3 },
  },
  {
    id: "toyota",
    name: "Toyota",
    tag: "Manufacturing",
    rating: 4.1,
    reviewCount: 13,
    recommendCount: 9,
    scores: { work: 4.0, social: 4.1, mentor: 4.0, experience: 4.2 },
  },
  {
    id: "cpf",
    name: "CPF",
    tag: "Manufacturing",
    rating: 3.9,
    reviewCount: 8,
    recommendCount: 6,
    scores: { work: 3.8, social: 4.0, mentor: 3.9, experience: 4.0 },
  },
  {
    id: "mitr-phol",
    name: "Mitr Phol",
    tag: "Manufacturing",
    rating: 4.1,
    reviewCount: 7,
    recommendCount: 6,
    scores: { work: 4.0, social: 4.0, mentor: 4.1, experience: 4.2 },
  },
  {
    id: "bangchak",
    name: "Bangchak",
    tag: "Energy",
    rating: 4.2,
    reviewCount: 9,
    recommendCount: 7,
    scores: { work: 4.1, social: 4.3, mentor: 4.2, experience: 4.3 },
  },
  {
    id: "true-digital",
    name: "True Digital",
    tag: "Media",
    rating: 4.1,
    reviewCount: 13,
    recommendCount: 9,
    scores: { work: 4.2, social: 4.0, mentor: 4.0, experience: 4.2 },
  },
  {
    id: "kbank",
    name: "KBank",
    tag: "Banking",
    rating: 4.3,
    reviewCount: 16,
    recommendCount: 12,
    scores: { work: 4.2, social: 4.2, mentor: 4.1, experience: 4.4 },
  },
  {
    id: "scb",
    name: "SCB",
    tag: "Banking",
    rating: 4.2,
    reviewCount: 15,
    recommendCount: 11,
    scores: { work: 4.1, social: 4.1, mentor: 4.0, experience: 4.3 },
  },
  {
    id: "pttep",
    name: "PTTEP",
    tag: "Energy",
    rating: 4.4,
    reviewCount: 11,
    recommendCount: 9,
    scores: { work: 4.4, social: 4.2, mentor: 4.3, experience: 4.5 },
  },
  {
    id: "central-group",
    name: "Central Group",
    tag: "Retail",
    rating: 4.0,
    reviewCount: 10,
    recommendCount: 7,
    scores: { work: 3.9, social: 4.1, mentor: 3.9, experience: 4.0 },
  },
  {
    id: "dtac",
    name: "DTAC",
    tag: "Telecom",
    rating: 4.1,
    reviewCount: 9,
    recommendCount: 6,
    scores: { work: 4.0, social: 4.1, mentor: 4.0, experience: 4.1 },
  },
  {
    id: "grab-thailand",
    name: "Grab Thailand",
    tag: "Logistics",
    rating: 4.4,
    reviewCount: 14,
    recommendCount: 12,
    scores: { work: 4.5, social: 4.3, mentor: 4.2, experience: 4.6 },
  },
  {
    id: "lazada",
    name: "Lazada",
    tag: "E-com",
    rating: 4.2,
    reviewCount: 12,
    recommendCount: 9,
    scores: { work: 4.3, social: 4.0, mentor: 4.0, experience: 4.3 },
  },
  {
    id: "deloitte",
    name: "Deloitte",
    tag: "Consulting",
    rating: 4.0,
    reviewCount: 10,
    recommendCount: 7,
    scores: { work: 4.1, social: 3.9, mentor: 3.8, experience: 4.0 },
  },
  {
    id: "pwc",
    name: "PwC",
    tag: "Consulting",
    rating: 3.9,
    reviewCount: 9,
    recommendCount: 6,
    scores: { work: 4.0, social: 3.8, mentor: 3.7, experience: 3.9 },
  },
  {
    id: "ibm-thailand",
    name: "IBM Thailand",
    tag: "Tech",
    rating: 4.1,
    reviewCount: 8,
    recommendCount: 6,
    scores: { work: 4.1, social: 4.0, mentor: 4.1, experience: 4.2 },
  },
  {
    id: "microsoft-thailand",
    name: "Microsoft Thailand",
    tag: "Tech",
    rating: 4.6,
    reviewCount: 13,
    recommendCount: 12,
    scores: { work: 4.7, social: 4.5, mentor: 4.6, experience: 4.8 },
  },
  {
    id: "nectec",
    name: "NECTEC",
    tag: "AI / Data",
    rating: 4.3,
    reviewCount: 7,
    recommendCount: 6,
    scores: { work: 4.4, social: 4.1, mentor: 4.3, experience: 4.3 },
  },
  {
    id: "thai-airways",
    name: "Thai Airways",
    tag: "Travel",
    rating: 3.9,
    reviewCount: 8,
    recommendCount: 5,
    scores: { work: 3.8, social: 4.0, mentor: 3.8, experience: 3.9 },
  },
  {
    id: "boonrawd-brewery",
    name: "Boonrawd Brewery",
    tag: "Manufacturing",
    rating: 4.1,
    reviewCount: 7,
    recommendCount: 5,
    scores: { work: 4.0, social: 4.2, mentor: 4.0, experience: 4.1 },
  },
  {
    id: "central-pattana",
    name: "Central Pattana",
    tag: "Real Estate",
    rating: 4.0,
    reviewCount: 9,
    recommendCount: 6,
    scores: { work: 3.9, social: 4.1, mentor: 4.0, experience: 4.0 },
  },
  {
    id: "big-c",
    name: "Big C",
    tag: "Retail",
    rating: 3.8,
    reviewCount: 6,
    recommendCount: 4,
    scores: { work: 3.7, social: 3.9, mentor: 3.7, experience: 3.8 },
  },
  {
    id: "unilever-thailand",
    name: "Unilever Thailand",
    tag: "Manufacturing",
    rating: 4.3,
    reviewCount: 11,
    recommendCount: 9,
    scores: { work: 4.3, social: 4.2, mentor: 4.2, experience: 4.4 },
  },
];

export const reviews: Review[] = [
  {
    id: "data-engineer-intern",
    companyId: "line-man-wongnai",
    name: "Anonymous",
    department: "ภาคคอมพิวเตอร์",
    intania: "107",
    daysAgo: 7,
    recommended: true,
    position: "Data Engineer Intern",
    duration: "3 เดือน",
    compensation: "500 บาท/วัน",
    workMode: "Work from home",
    openYears: "ทุกชั้นปี",
    minGpa: null,
    scores: { work: 5, social: 4, mentor: 2, experience: 5 },
    sections: {
      application:
        "สมัครผ่านเว็บไซต์บริษัท แล้วมีทั้งหมด 2 รอบ คือรอบ resume screening กับสัมภาษณ์ 1 รอบ ใช้เวลาประมาณ 2 อาทิตย์กว่าจะได้ผลสัมภาษณ์ ตอนสัมภาษณ์จะถามทั้งเรื่องพื้นฐานที่เกี่ยวกับตำแหน่ง และถามพฤติกรรมการทำงานด้วย ถ้าจะเตรียมตัว แนะนำให้ทำความเข้าใจงานของบริษัทกับทบทวนโปรเจกต์ที่เคยทำไปก่อน เพราะมีโอกาสโดนถามลึกพอสมควร",
      work:
        "ได้ช่วยงานหลักของทีมจริง ไม่ได้เป็นงานเบ็ดเตล็ดอย่างเดียว มีทั้งงานย่อยที่ให้รับผิดชอบเองและงานที่ทำร่วมกับพี่ในทีม ได้ลองใช้เครื่องมือที่ทีมใช้งานจริง รวมถึงได้เห็น flow การทำงานตั้งแต่รับ requirement ไปจนถึงส่งงาน เนื้องานโดยรวมค่อนข้างตรงกับตำแหน่งที่สมัคร และได้เรียนรู้เพิ่มจากของที่ไม่เคยใช้มาก่อนพอสมควร",
      atmosphere:
        "บรรยากาศในทีมค่อนข้างเป็นกันเอง พี่ ๆ พร้อมตอบคำถามและไม่ได้ทำให้รู้สึกเกร็งเกินไป การสื่อสารในทีมชัดเจนและตามงานกันพอดี วัฒนธรรมการทำงานค่อนข้าง professional แต่ไม่ได้กดดันเกิน",
      welfare:
        "เนื่องจากเป็น Work from home เกือบทั้งหมด เลยแทบไม่มีปัญหาเรื่องการเดินทาง มีค่าเดินทางให้กรณีต้อง onsite และมีอุปกรณ์คอมพิวเตอร์ให้ยืมใช้ระหว่างฝึกงาน สวัสดิการถือว่าโอเคสำหรับ intern",
      advice:
        "สิ่งที่ชอบคือได้ทำงานจริงและเห็นภาพการทำงานในบริษัทชัดเจนขึ้นมาก สิ่งที่ไม่ชอบคือบางช่วงงานค่อนข้างเร็ว ทำให้ต้องปรับตัวพอสมควร สิ่งที่ได้เรียนรู้มากที่สุดคือการทำงานร่วมกับทีมและการสื่อสารในบริบทงานจริง ถ้าใครสนใจสมัคร แนะนำให้เตรียมพื้นฐานที่เกี่ยวกับตำแหน่งไปให้แน่น และอย่ากลัวที่จะถามเวลามีอะไรไม่เข้าใจ เพราะยิ่งถามเร็วก็ยิ่งเรียนรู้ได้เร็วครับ",
    },
  },
  {
    id: "backend-intern",
    companyId: "line-man-wongnai",
    name: "Anonymous",
    department: "ภาคไฟฟ้า",
    intania: "106",
    daysAgo: 12,
    recommended: true,
    position: "Backend Intern",
    duration: "2 เดือน",
    compensation: "18,000 บาท/เดือน",
    workMode: "Hybrid",
    openYears: "ชั้นปีที่ 3-4",
    minGpa: 2.75,
    scores: { work: 4, social: 4, mentor: 3, experience: 4 },
    sections: {
      application: "สมัครผ่าน referral แล้วมี screening กับ technical interview รวมใช้เวลาประมาณหนึ่งสัปดาห์",
      work: "ได้ช่วยพัฒนา feature ย่อยใน service จริง มี code review และได้คุยกับทีม product บางช่วง งานค่อนข้างตรงกับตำแหน่งที่สมัคร แต่ช่วงแรกต้องใช้เวลาเข้าใจระบบเยอะพอสมควร",
      atmosphere: "ทีมคุยง่ายและช่วยกันดี มี standup สั้น ๆ ทำให้เห็นภาพงานของทีมชัด",
      welfare: "ออฟฟิศอยู่ใกล้ BTS เดินทางสะดวกมาก มีที่จอดรถให้พนักงาน สวัสดิการมีอาหารกลางวันฟรีทุกวันและมีเครื่องดื่ม/ขนมในออฟฟิศให้ตลอดเวลา",
      advice: "เตรียมพื้นฐาน backend, database และโปรเจกต์ที่เคยทำไว้เล่าให้กระชับจะช่วยได้มาก",
    },
  },
  {
    id: "product-design-intern-agoda",
    companyId: "agoda",
    name: "Anonymous",
    department: "ภาคคอมพิวเตอร์",
    intania: "108",
    daysAgo: 1,
    recommended: true,
    position: "Product Design Intern",
    duration: "4 เดือน",
    compensation: "25,000 บาท/เดือน",
    workMode: "Hybrid",
    openYears: "ทุกชั้นปี",
    minGpa: null,
    scores: { work: 5, social: 4, mentor: 4, experience: 5 },
    sections: {
      application: "สมัครผ่านเว็บไซต์บริษัท มี portfolio review รอบแรกแล้วตามด้วยสัมภาษณ์ 2 รอบ ใช้เวลารวมประมาณ 3 อาทิตย์ เตรียม case study ของงานที่เคยทำไปนำเสนอจะช่วยได้มาก",
      work: "ได้ทำ feature จริงตั้งแต่ research ไปจนถึง handoff ให้ทีม dev ได้เรียนรู้ design system ของบริษัทและได้ present งานให้ stakeholder ฟังหลายรอบ",
      atmosphere: "ทีม design ช่วยเหลือกันดีและให้ feedback ตรงไปตรงมา",
      welfare: "ออฟฟิศ Agoda อยู่ใจกลางเมือง เดินทางด้วย BTS สะดวกมาก สวัสดิการดีมาก มีอาหารกลางวันฟรี ห้องนอนพัก ห้องเกม และมี gym ให้ใช้ฟรีในตึกด้วย",
      advice: "ถ้าสนใจสาย design แนะนำให้เตรียม portfolio ให้ดีและฝึกเล่าเหตุผลเบื้องหลังงานออกแบบให้ชัดเจน",
    },
  },
  {
    id: "data-analyst-intern-agoda",
    companyId: "agoda",
    name: "Anonymous",
    department: "ภาคอุตสาหการ",
    intania: "107",
    daysAgo: 14,
    recommended: true,
    position: "Data Analyst Intern",
    duration: "3 เดือน",
    compensation: "22,000 บาท/เดือน",
    workMode: "Onsite",
    openYears: "ชั้นปีที่ 3-4",
    minGpa: 3.0,
    scores: { work: 4, social: 4, mentor: 4, experience: 5 },
    sections: {
      application: "สมัครผ่านเว็บไซต์ มี online assessment ก่อนแล้วตามด้วยสัมภาษณ์ 2 รอบ",
      work: "ได้ทำ dashboard และวิเคราะห์ข้อมูลจริงให้ทีม marketing ใช้ตัดสินใจ เนื้องานท้าทายและได้ใช้ SQL กับ Python เยอะมาก",
      atmosphere: "บริษัทใหญ่ ระบบชัดเจน พี่เลี้ยงใจดีและตามงานสม่ำเสมอ",
      welfare: "เดินทางสะดวกเพราะติด BTS สวัสดิการเทียบเท่าพนักงานประจำเกือบทุกอย่าง มีอาหารกลางวันฟรี และมีส่วนลดโรงแรมผ่านแพลตฟอร์มของบริษัทด้วย",
      advice: "เตรียมพื้นฐาน SQL ให้แน่นเพราะใช้จริงตั้งแต่วันแรก",
    },
  },
  {
    id: "software-engineer-intern-scb-techx",
    companyId: "scb-techx",
    name: "Anonymous",
    department: "ภาคคอมพิวเตอร์",
    intania: "106",
    daysAgo: 3,
    recommended: true,
    position: "Software Engineer Intern",
    duration: "4 เดือน",
    compensation: "20,000 บาท/เดือน",
    workMode: "Hybrid",
    openYears: "ชั้นปีที่ 3-4",
    minGpa: 2.5,
    scores: { work: 4, social: 4, mentor: 4, experience: 4 },
    sections: {
      application: "สมัครผ่านเว็บไซต์บริษัท มี technical test แล้วตามด้วยสัมภาษณ์ 2 รอบ ใช้เวลาประมาณ 2 อาทิตย์",
      work: "ได้พัฒนา microservice เล็ก ๆ ในระบบจริง มี code review ทุกครั้งและได้เรียนรู้ best practice เยอะ",
      atmosphere: "ทีมเป็นกันเองมาก มี session แบ่งปันความรู้ทุกสัปดาห์",
      welfare: "ออฟฟิศอยู่แถว True Digital Park เดินทางด้วยรถไฟฟ้าสายสีเหลืองได้เลย สวัสดิการมีค่าอาหารกลางวันและมีพื้นที่ทำงานที่ทันสมัย สบายเวลานั่งทำงานนาน ๆ",
      advice: "เตรียมพื้นฐาน OOP และ database ให้แน่น เพราะโจทย์ทดสอบค่อนข้างเน้นพื้นฐาน",
    },
  },
  {
    id: "qa-engineer-intern-shopee",
    companyId: "shopee",
    name: "Anonymous",
    department: "ภาคคอมพิวเตอร์",
    intania: "108",
    daysAgo: 5,
    recommended: true,
    position: "QA Engineer Intern",
    duration: "3 เดือน",
    compensation: "18,000 บาท/เดือน",
    workMode: "Onsite",
    openYears: "ทุกชั้นปี",
    minGpa: null,
    scores: { work: 4, social: 5, mentor: 4, experience: 5 },
    sections: {
      application: "สมัครผ่านเว็บไซต์ มีสัมภาษณ์ 2 รอบ รอบแรกคุยเรื่อง background รอบสองเป็น technical",
      work: "ได้เขียน automated test และช่วยหา bug ในระบบจริงก่อนขึ้น production ได้เห็น flow การทำงานของทีม dev และ QA ชัดเจน",
      atmosphere: "บรรยากาศสนุก พี่ ๆ ในทีมกันเองและมีกิจกรรมบ่อย ออฟฟิศสะดวกสบาย",
      welfare: "ออฟฟิศ Shopee เดินทางด้วยรถไฟฟ้าสะดวก มีรถรับส่งจากสถานีด้วย สวัสดิการมีอาหารกลางวันฟรีและมีมุมพักผ่อนหลายจุดในออฟฟิศ",
      advice: "เตรียมพื้นฐานการเขียนโค้ดเบื้องต้นไปด้วย จะช่วยให้เข้าใจงาน automation ได้เร็วขึ้น",
    },
  },
  {
    id: "marketing-intern-shopee",
    companyId: "shopee",
    name: "Anonymous",
    department: "ภาคเคมี",
    intania: "105",
    daysAgo: 20,
    recommended: false,
    position: "Marketing Intern",
    duration: "2 เดือน",
    compensation: "15,000 บาท/เดือน",
    workMode: "Onsite",
    openYears: "ชั้นปีที่ 3-4",
    minGpa: 2.5,
    scores: { work: 3, social: 4, mentor: 3, experience: 3 },
    sections: {
      application: "สมัครผ่าน career fair ของมหาวิทยาลัย มีสัมภาษณ์รอบเดียว",
      work: "งานส่วนใหญ่เป็นงานเอกสารและช่วยเตรียมแคมเปญ ไม่ค่อยได้ลงมือทำเองเท่าที่คาดหวังไว้",
      atmosphere: "ทีมใจดีแต่ค่อนข้างยุ่ง บางครั้งไม่มีเวลาสอนงานมากนัก",
      welfare: "การเดินทางสะดวกเพราะมีรถรับส่งจากสถานีรถไฟฟ้า สวัสดิการพื้นฐานมีอาหารกลางวัน แต่ไม่ได้มีอะไรพิเศษเพิ่มเติมมากนักสำหรับตำแหน่ง intern",
      advice: "ถ้าอยากได้ประสบการณ์ hands-on เยอะ ๆ อาจต้องถามรายละเอียดงานก่อนตอบรับ",
    },
  },
  {
    id: "process-engineer-intern-scg",
    companyId: "scg",
    name: "Anonymous",
    department: "ภาคเคมี",
    intania: "107",
    daysAgo: 9,
    recommended: true,
    position: "Process Engineer Intern",
    duration: "2 เดือน",
    compensation: "15,000 บาท/เดือน",
    workMode: "Onsite",
    openYears: "ชั้นปีที่ 3-4",
    minGpa: 2.5,
    scores: { work: 4, social: 4, mentor: 4, experience: 4 },
    sections: {
      application: "สมัครผ่านเว็บไซต์บริษัท มีสอบข้อเขียนและสัมภาษณ์รวม 2 รอบ",
      work: "ได้ลงพื้นที่โรงงานจริงและช่วยวิเคราะห์ปัญหากระบวนการผลิต ได้ใช้ความรู้ที่เรียนมาโดยตรง",
      atmosphere: "พี่ ๆ ในโรงงานใจดีและสอนงานละเอียด แต่ต้องปรับตัวกับเวลาทำงานแบบกะบ้าง",
      welfare: "โรงงานอยู่นอกเมือง ต้องมีรถส่วนตัวหรือใช้รถรับส่งของบริษัทที่จัดให้จากจุดนัดพบ สวัสดิการมีอาหารกลางวันและชุดฝึกงาน (PPE) ให้ครบ",
      advice: "เตรียมความรู้พื้นฐานวิศวกรรมเคมีให้แน่น และเตรียมใจเรื่องการเดินทางไปโรงงาน",
    },
  },
  {
    id: "mechanical-engineer-intern-ptt",
    companyId: "ptt",
    name: "Anonymous",
    department: "ภาคเครื่องกล",
    intania: "106",
    daysAgo: 25,
    recommended: true,
    position: "Mechanical Engineer Intern",
    duration: "2 เดือน",
    compensation: "16,000 บาท/เดือน",
    workMode: "Onsite",
    openYears: "ชั้นปีที่ 3-4",
    minGpa: 2.75,
    scores: { work: 4, social: 4, mentor: 4, experience: 4 },
    sections: {
      application: "สมัครผ่านโครงการฝึกงานของบริษัท มีสัมภาษณ์ 1 รอบ",
      work: "ได้ช่วยงานบำรุงรักษาเครื่องจักรและติดตามโปรเจกต์ปรับปรุงประสิทธิภาพ เนื้องานตรงกับสายที่เรียนมา",
      atmosphere: "องค์กรใหญ่ ระบบชัดเจน พี่เลี้ยงดูแลดี",
      welfare: "สวัสดิการดีสมกับเป็นองค์กรใหญ่ มีอาหารกลางวัน ที่พักสำหรับ intern ต่างจังหวัด และมีรถรับส่งระหว่างที่พักกับโรงงานให้ทุกวัน",
      advice: "เตรียมตัวเรื่องความปลอดภัยในโรงงานให้ดี เพราะมีการอบรมและข้อกำหนดค่อนข้างเยอะ",
    },
  },
  {
    id: "audit-intern-ey",
    companyId: "ey",
    name: "Anonymous",
    department: "ภาคอุตสาหการ",
    intania: "108",
    daysAgo: 4,
    recommended: true,
    position: "Audit Intern",
    duration: "3 เดือน",
    compensation: "17,000 บาท/เดือน",
    workMode: "Hybrid",
    openYears: "ทุกชั้นปี",
    minGpa: null,
    scores: { work: 4, social: 4, mentor: 3, experience: 4 },
    sections: {
      application: "สมัครผ่านเว็บไซต์บริษัท มีแบบทดสอบออนไลน์และสัมภาษณ์ 2 รอบ",
      work: "ได้ร่วมทีมตรวจสอบบัญชีลูกค้าจริง งานค่อนข้างละเอียดและต้องรอบคอบสูง",
      atmosphere: "งานค่อนข้างหนักในบางช่วง แต่พี่ ๆ ในทีมพร้อมสอนงานและตอบคำถามเสมอ",
      welfare: "ออฟฟิศอยู่ในตัวเมือง เดินทางด้วย BTS ได้เลย สวัสดิการมีค่าอาหารกลางวันและ allowance เพิ่มเติมเวลาต้องออกไปหาลูกค้านอกสถานที่",
      advice: "เตรียมพื้นฐานบัญชีให้แน่นและฝึกใช้ Excel ให้คล่อง จะช่วยได้เยอะมาก",
    },
  },
  {
    id: "network-engineer-intern-ais",
    companyId: "ais",
    name: "Anonymous",
    department: "ภาคไฟฟ้า",
    intania: "107",
    daysAgo: 30,
    recommended: true,
    position: "Network Engineer Intern",
    duration: "3 เดือน",
    compensation: "16,000 บาท/เดือน",
    workMode: "Hybrid",
    openYears: "ชั้นปีที่ 3-4",
    minGpa: 2.5,
    scores: { work: 4, social: 4, mentor: 4, experience: 4 },
    sections: {
      application: "สมัครผ่านเว็บไซต์บริษัท มีสัมภาษณ์ 2 รอบ เน้นถามพื้นฐาน networking",
      work: "ได้เรียนรู้ระบบเครือข่ายจริงของบริษัทและช่วยทีม monitor คุณภาพสัญญาณ",
      atmosphere: "ทีมใจดี พร้อมสอนงานตั้งแต่พื้นฐาน บรรยากาศไม่กดดัน",
      welfare: "ออฟฟิศอยู่ใกล้ BTS หมอชิต เดินทางง่าย สวัสดิการมีอาหารกลางวันและส่วนลดค่าโทรศัพท์/อินเทอร์เน็ตของบริษัทให้ intern ด้วย",
      advice: "เตรียมพื้นฐานเรื่อง network protocol ไปบ้างจะช่วยให้ตามงานทันเร็วขึ้น",
    },
  },
  {
    id: "quality-engineer-intern-toyota",
    companyId: "toyota",
    name: "Anonymous",
    department: "ภาคเครื่องกล",
    intania: "106",
    daysAgo: 18,
    recommended: true,
    position: "Quality Engineer Intern",
    duration: "2 เดือน",
    compensation: "15,000 บาท/เดือน",
    workMode: "Onsite",
    openYears: "ชั้นปีที่ 3-4",
    minGpa: 2.75,
    scores: { work: 4, social: 4, mentor: 4, experience: 4 },
    sections: {
      application: "สมัครผ่านโครงการความร่วมมือกับมหาวิทยาลัย มีสัมภาษณ์ 1 รอบ",
      work: "ได้ลงไลน์ผลิตจริงและช่วยตรวจสอบคุณภาพชิ้นงาน ได้เห็นระบบ lean manufacturing ของญี่ปุ่นแบบใกล้ชิด",
      atmosphere: "ระเบียบวินัยสูง พี่ ๆ ใจดีและสอนงานเป็นขั้นตอนชัดเจน",
      welfare: "โรงงานอยู่ต่างจังหวัด ถ้าไม่มีรถส่วนตัวค่อนข้างลำบาก แต่บริษัทมีรถรับส่งจากจุดนัดพบในตัวเมืองให้ สวัสดิการมีอาหารกลางวันและชุดยูนิฟอร์มให้ใช้ตลอดโปรแกรม",
      advice: "เตรียมใจเรื่องความมีระเบียบวินัยและตรงต่อเวลา เพราะวัฒนธรรมองค์กรค่อนข้างเข้มงวด",
    },
  },
  {
    id: "food-science-intern-cpf",
    companyId: "cpf",
    name: "Anonymous",
    department: "ภาคเคมี",
    intania: "108",
    daysAgo: 22,
    recommended: true,
    position: "Food Science Intern",
    duration: "2 เดือน",
    compensation: "13,000 บาท/เดือน",
    workMode: "Onsite",
    openYears: "ทุกชั้นปี",
    minGpa: null,
    scores: { work: 4, social: 4, mentor: 4, experience: 4 },
    sections: {
      application: "สมัครผ่านเว็บไซต์บริษัท มีสัมภาษณ์รอบเดียว",
      work: "ได้ช่วยงานวิจัยและพัฒนาสูตรผลิตภัณฑ์ใหม่ในแล็บ ได้ทดลองจริงหลายครั้ง",
      atmosphere: "ทีมเล็กแต่อบอุ่น พี่ ๆ ดูแลดีและอธิบายละเอียด",
      welfare: "โรงงาน/แล็บอยู่ชานเมือง เดินทางด้วยรถส่วนตัวสะดวกกว่า สวัสดิการมีอาหารกลางวันฟรีและชุดแล็บให้ใช้ระหว่างฝึกงาน",
      advice: "ถ้าสนใจงานแล็บ เตรียมพื้นฐานเคมีอาหารไปบ้างจะช่วยให้เข้าใจงานเร็วขึ้น",
    },
  },
  {
    id: "process-intern-mitr-phol",
    companyId: "mitr-phol",
    name: "Anonymous",
    department: "ภาคเคมี",
    intania: "105",
    daysAgo: 35,
    recommended: true,
    position: "Process Engineer Intern",
    duration: "2 เดือน",
    compensation: "14,000 บาท/เดือน",
    workMode: "Onsite",
    openYears: "ชั้นปีที่ 3-4",
    minGpa: 2.5,
    scores: { work: 4, social: 4, mentor: 4, experience: 4 },
    sections: {
      application: "สมัครผ่านอาจารย์แนะนำ มีสัมภาษณ์กับหัวหน้าแผนกโดยตรง",
      work: "ได้ลงพื้นที่โรงงานน้ำตาลจริงและช่วยเก็บข้อมูลกระบวนการผลิตเพื่อวิเคราะห์ประสิทธิภาพ",
      atmosphere: "บรรยากาศเป็นกันเองแบบโรงงานต่างจังหวัด พี่ ๆ ดูแลดีมาก",
      welfare: "โรงงานอยู่ต่างจังหวัดไกลจากกรุงเทพมาก บริษัทจัดที่พักให้ intern ฟรีตลอดโปรแกรมและมีรถรับส่งระหว่างที่พักกับโรงงานให้ทุกวัน ถือว่าสวัสดิการเรื่องที่อยู่ดีมาก",
      advice: "เตรียมใจเรื่องที่พักและการเดินทางเพราะโรงงานอยู่ต่างจังหวัด",
    },
  },
  {
    id: "sustainability-intern-bangchak",
    companyId: "bangchak",
    name: "Anonymous",
    department: "ภาคสิ่งแวดล้อม",
    intania: "107",
    daysAgo: 27,
    recommended: true,
    position: "Sustainability Intern",
    duration: "2 เดือน",
    compensation: "14,000 บาท/เดือน",
    workMode: "Hybrid",
    openYears: "ทุกชั้นปี",
    minGpa: null,
    scores: { work: 4, social: 4, mentor: 4, experience: 4 },
    sections: {
      application: "สมัครผ่านเว็บไซต์บริษัท มีสัมภาษณ์ 1 รอบ",
      work: "ได้ช่วยทำรายงานความยั่งยืนและร่วมโปรเจกต์ลดคาร์บอนของบริษัท ได้เห็นภาพรวมธุรกิจพลังงานสะอาด",
      atmosphere: "ทีมเปิดกว้างรับฟังไอเดียใหม่ ๆ บรรยากาศทำงานสบาย ๆ",
      welfare: "ออฟฟิศอยู่ใกล้ BTS อ่อนนุช เดินทางสะดวก สวัสดิการมีอาหารกลางวันฟรีและมีกิจกรรม CSR ให้ intern เข้าร่วมได้ด้วย",
      advice: "ถ้าสนใจสาย sustainability งานนี้เปิดโอกาสให้เสนอไอเดียได้เยอะ ลองเตรียมมุมมองของตัวเองไปคุยด้วย",
    },
  },
  {
    id: "content-intern-true-digital",
    companyId: "true-digital",
    name: "Anonymous",
    department: "ภาคคอมพิวเตอร์",
    intania: "108",
    daysAgo: 40,
    recommended: false,
    position: "Digital Content Intern",
    duration: "3 เดือน",
    compensation: "13,000 บาท/เดือน",
    workMode: "Hybrid",
    openYears: "ชั้นปีที่ 3-4",
    minGpa: 2.5,
    scores: { work: 3, social: 3, mentor: 3, experience: 3 },
    sections: {
      application: "สมัครผ่านเว็บไซต์บริษัท มีสัมภาษณ์รอบเดียว",
      work: "งานหลักเป็นการช่วยทำ content และตัดต่อวิดีโอสั้น ๆ เนื้องานค่อนข้างซ้ำ ไม่ค่อยหลากหลาย",
      atmosphere: "พี่ ๆ ใจดีแต่ทีมค่อนข้างเล็กและงานยุ่ง บางครั้งไม่มีเวลาให้ feedback",
      welfare: "ออฟฟิศอยู่ที่ True Digital Park เดินทางด้วยรถไฟฟ้าสายสีเหลืองสะดวก สวัสดิการมีอาหารกลางวันฟรี แต่ไม่ได้มีอะไรเพิ่มเติมมากสำหรับ intern",
      advice: "ถามรายละเอียดขอบเขตงานให้ชัดก่อนตอบรับ เพื่อดูว่าตรงกับที่คาดหวังไหม",
    },
  },
  {
    id: "credit-analyst-intern-kbank",
    companyId: "kbank",
    name: "Anonymous",
    department: "ภาคอุตสาหการ",
    intania: "107",
    daysAgo: 2,
    recommended: true,
    position: "Credit Analyst Intern",
    duration: "3 เดือน",
    compensation: "18,000 บาท/เดือน",
    workMode: "Hybrid",
    openYears: "ชั้นปีที่ 3-4",
    minGpa: 2.75,
    scores: { work: 4, social: 4, mentor: 4, experience: 4 },
    sections: {
      application: "สมัครผ่านเว็บไซต์บริษัท มีแบบทดสอบออนไลน์และสัมภาษณ์ 2 รอบ",
      work: "ได้ช่วยวิเคราะห์ข้อมูลสินเชื่อลูกค้าจริงและทำสรุปเสนอทีม ได้ใช้ Excel และเรียนรู้กระบวนการอนุมัติสินเชื่อ",
      atmosphere: "องค์กรใหญ่ ระบบชัดเจน พี่เลี้ยงดูแลดีและตอบคำถามเสมอ",
      welfare: "ออฟฟิศอยู่ใจกลางเมือง เดินทางสะดวกด้วยรถไฟฟ้า สวัสดิการมีอาหารกลางวันและส่วนลดผลิตภัณฑ์ทางการเงินของธนาคารให้พนักงานฝึกงานด้วย",
      advice: "เตรียมพื้นฐานการเงินและ Excel ให้แน่น จะช่วยให้ทำงานได้เร็วขึ้น",
    },
  },
  {
    id: "business-analyst-intern-scb",
    companyId: "scb",
    name: "Anonymous",
    department: "ภาคคอมพิวเตอร์",
    intania: "108",
    daysAgo: 6,
    recommended: true,
    position: "Business Analyst Intern",
    duration: "4 เดือน",
    compensation: "20,000 บาท/เดือน",
    workMode: "Hybrid",
    openYears: "ชั้นปีที่ 3-4",
    minGpa: 2.75,
    scores: { work: 4, social: 4, mentor: 4, experience: 4 },
    sections: {
      application: "สมัครผ่านเว็บไซต์บริษัท มีสัมภาษณ์ 2 รอบและ case study",
      work: "ได้ร่วมวิเคราะห์ requirement ของโปรเจกต์ digital banking และประสานงานกับทีม dev",
      atmosphere: "ทีมทันสมัย เปิดรับไอเดียใหม่ ๆ พี่ ๆ เป็นกันเอง",
      welfare: "ออฟฟิศอยู่ติด BTS เดินทางง่ายมาก สวัสดิการมีอาหารกลางวันฟรีและมีพื้นที่ co-working สมัยใหม่ให้ทำงานสบาย ๆ",
      advice: "เตรียมทักษะการนำเสนอและวิเคราะห์ข้อมูลไปด้วย จะช่วยได้มาก",
    },
  },
  {
    id: "petroleum-engineer-intern-pttep",
    companyId: "pttep",
    name: "Anonymous",
    department: "ภาคเหมืองแร่",
    intania: "106",
    daysAgo: 33,
    recommended: true,
    position: "Petroleum Engineer Intern",
    duration: "2 เดือน",
    compensation: "17,000 บาท/เดือน",
    workMode: "Onsite",
    openYears: "ชั้นปีที่ 3-4",
    minGpa: 3.0,
    scores: { work: 5, social: 4, mentor: 4, experience: 5 },
    sections: {
      application: "สมัครผ่านเว็บไซต์บริษัท มีสัมภาษณ์ 2 รอบ เน้นความรู้เฉพาะทาง",
      work: "ได้ร่วมวิเคราะห์ข้อมูลแหล่งปิโตรเลียมจริงและเห็นภาพรวมธุรกิจสำรวจขุดเจาะ",
      atmosphere: "องค์กรมืออาชีพ พี่ ๆ เก่งและพร้อมสอน",
      welfare: "องค์กรใหญ่ สวัสดิการดีมาก มีอาหารกลางวันฟรี ที่พักและรถรับส่งให้กรณีต้องไปทำงานที่ site ต่างจังหวัด",
      advice: "เตรียมพื้นฐานวิชาที่เกี่ยวข้องให้แน่น เพราะงานค่อนข้างเฉพาะทาง",
    },
  },
  {
    id: "supply-chain-intern-central-group",
    companyId: "central-group",
    name: "Anonymous",
    department: "ภาคอุตสาหการ",
    intania: "108",
    daysAgo: 16,
    recommended: false,
    position: "Supply Chain Intern",
    duration: "2 เดือน",
    compensation: "14,000 บาท/เดือน",
    workMode: "Onsite",
    openYears: "ทุกชั้นปี",
    minGpa: null,
    scores: { work: 3, social: 4, mentor: 3, experience: 3 },
    sections: {
      application: "สมัครผ่านเว็บไซต์บริษัท มีสัมภาษณ์รอบเดียว",
      work: "ได้ช่วยวิเคราะห์ข้อมูล stock และประสานงานกับคลังสินค้า งานค่อนข้างกว้างและไม่ค่อยมีโครงสร้างชัดเจน",
      atmosphere: "ทีมใจดีแต่ค่อนข้างยุ่ง บางครั้งไม่มีคนตามงานให้",
      advice: "ถามขอบเขตงานให้ชัดก่อนเริ่ม เพื่อวางแผนการเรียนรู้ของตัวเอง",
    },
  },
  {
    id: "network-intern-dtac",
    companyId: "dtac",
    name: "Anonymous",
    department: "ภาคไฟฟ้า",
    intania: "107",
    daysAgo: 24,
    recommended: true,
    position: "Network Engineer Intern",
    duration: "3 เดือน",
    compensation: "16,000 บาท/เดือน",
    workMode: "Hybrid",
    openYears: "ชั้นปีที่ 3-4",
    minGpa: 2.5,
    scores: { work: 4, social: 4, mentor: 4, experience: 4 },
    sections: {
      application: "สมัครผ่านเว็บไซต์บริษัท มีสัมภาษณ์ 2 รอบ",
      work: "ได้ช่วยดูแลคุณภาพสัญญาณเครือข่ายและวิเคราะห์ข้อมูลการใช้งาน",
      atmosphere: "บรรยากาศสบาย ๆ พี่ ๆ ใจดี มีเวลาสอนงานเสมอ",
      advice: "เตรียมพื้นฐาน networking ไปบ้างจะช่วยให้ตามงานทันเร็วขึ้น",
    },
  },
  {
    id: "software-engineer-intern-grab",
    companyId: "grab-thailand",
    name: "Anonymous",
    department: "ภาคคอมพิวเตอร์",
    intania: "108",
    daysAgo: 8,
    recommended: true,
    position: "Software Engineer Intern",
    duration: "4 เดือน",
    compensation: "24,000 บาท/เดือน",
    workMode: "Hybrid",
    openYears: "ทุกชั้นปี",
    minGpa: null,
    scores: { work: 5, social: 4, mentor: 4, experience: 5 },
    sections: {
      application: "สมัครผ่านเว็บไซต์บริษัท มี technical test แล้วตามด้วยสัมภาษณ์ 2 รอบ",
      work: "ได้พัฒนา feature จริงในระบบ ride-hailing และ code review กับทีมทุกครั้ง เนื้องานท้าทายมาก",
      atmosphere: "ทีมอินเตอร์เนชันแนล บรรยากาศเปิดกว้าง เรียนรู้ได้เร็ว",
      advice: "เตรียมพื้นฐาน algorithm และ system design ไปด้วย จะช่วยตอนสัมภาษณ์มาก",
    },
  },
  {
    id: "data-analyst-intern-lazada",
    companyId: "lazada",
    name: "Anonymous",
    department: "ภาคอุตสาหการ",
    intania: "107",
    daysAgo: 19,
    recommended: true,
    position: "Data Analyst Intern",
    duration: "3 เดือน",
    compensation: "19,000 บาท/เดือน",
    workMode: "Hybrid",
    openYears: "ชั้นปีที่ 3-4",
    minGpa: 2.5,
    scores: { work: 4, social: 4, mentor: 4, experience: 4 },
    sections: {
      application: "สมัครผ่านเว็บไซต์บริษัท มี online assessment และสัมภาษณ์ 2 รอบ",
      work: "ได้วิเคราะห์ข้อมูลยอดขายและทำ dashboard ให้ทีม operations ใช้จริง",
      atmosphere: "ทีมกระตือรือร้น งานเร็วแต่พี่ ๆ ช่วยเหลือดี",
      advice: "เตรียม SQL และ data visualization ให้คล่อง จะช่วยได้เยอะ",
    },
  },
  {
    id: "consulting-intern-deloitte",
    companyId: "deloitte",
    name: "Anonymous",
    department: "ภาคอุตสาหการ",
    intania: "106",
    daysAgo: 29,
    recommended: true,
    position: "Consulting Intern",
    duration: "2 เดือน",
    compensation: "16,000 บาท/เดือน",
    workMode: "Hybrid",
    openYears: "ชั้นปีที่ 3-4",
    minGpa: 2.75,
    scores: { work: 4, social: 4, mentor: 3, experience: 4 },
    sections: {
      application: "สมัครผ่านเว็บไซต์บริษัท มี case interview 2 รอบ",
      work: "ได้ร่วมโปรเจกต์ให้คำปรึกษาลูกค้าจริง ช่วยทำ research และเตรียม presentation",
      atmosphere: "งานหนักแต่ได้เรียนรู้เยอะ พี่ ๆ เก่งและพร้อมสอน",
      advice: "ฝึกทักษะ PowerPoint และการวิเคราะห์เชิงธุรกิจไปด้วยจะช่วยมาก",
    },
  },
  {
    id: "audit-intern-pwc",
    companyId: "pwc",
    name: "Anonymous",
    department: "ภาคอุตสาหการ",
    intania: "108",
    daysAgo: 37,
    recommended: false,
    position: "Audit Intern",
    duration: "3 เดือน",
    compensation: "15,000 บาท/เดือน",
    workMode: "Onsite",
    openYears: "ชั้นปีที่ 3-4",
    minGpa: 2.75,
    scores: { work: 3, social: 3, mentor: 3, experience: 3 },
    sections: {
      application: "สมัครผ่านเว็บไซต์บริษัท มีแบบทดสอบและสัมภาษณ์ 2 รอบ",
      work: "งานส่วนใหญ่เป็นเอกสารและตรวจสอบข้อมูลพื้นฐาน ไม่ค่อยหลากหลาย",
      atmosphere: "งานค่อนข้างหนักในบาง season พี่ ๆ ใจดีแต่ไม่ค่อยมีเวลา",
      advice: "เตรียมใจเรื่องชั่วโมงงานที่อาจจะยาวในบางช่วง",
    },
  },
  {
    id: "cloud-engineer-intern-ibm",
    companyId: "ibm-thailand",
    name: "Anonymous",
    department: "ภาคคอมพิวเตอร์",
    intania: "107",
    daysAgo: 21,
    recommended: true,
    position: "Cloud Engineer Intern",
    duration: "3 เดือน",
    compensation: "18,000 บาท/เดือน",
    workMode: "Hybrid",
    openYears: "ทุกชั้นปี",
    minGpa: null,
    scores: { work: 4, social: 4, mentor: 4, experience: 4 },
    sections: {
      application: "สมัครผ่านเว็บไซต์บริษัท มีสัมภาษณ์ 2 รอบ",
      work: "ได้ทดลองใช้ cloud service จริงและช่วย deploy ระบบเล็ก ๆ ให้ทีม",
      atmosphere: "องค์กรใหญ่ ระบบชัดเจน พี่เลี้ยงดูแลดี",
      advice: "เตรียมพื้นฐาน cloud computing และ Linux ไปบ้างจะช่วยได้มาก",
    },
  },
  {
    id: "software-engineer-intern-microsoft",
    companyId: "microsoft-thailand",
    name: "Anonymous",
    department: "ภาคคอมพิวเตอร์",
    intania: "108",
    daysAgo: 0,
    recommended: true,
    position: "Software Engineer Intern",
    duration: "4 เดือน",
    compensation: "28,000 บาท/เดือน",
    workMode: "Hybrid",
    openYears: "ทุกชั้นปี",
    minGpa: 3.0,
    scores: { work: 5, social: 5, mentor: 5, experience: 5 },
    sections: {
      application: "สมัครผ่านเว็บไซต์บริษัท มี technical interview 3 รอบ ค่อนข้างท้าทาย",
      work: "ได้ทำโปรเจกต์จริงร่วมกับทีมและมี mentor ดูแลใกล้ชิดตลอดโปรแกรม",
      atmosphere: "วัฒนธรรมองค์กรดีมาก เปิดกว้าง สนับสนุนการเรียนรู้เต็มที่",
      advice: "เตรียมพื้นฐาน algorithm และ system design ให้แน่น การเตรียมตัวสัมภาษณ์สำคัญมาก",
    },
  },
  {
    id: "research-intern-nectec",
    companyId: "nectec",
    name: "Anonymous",
    department: "ภาคไฟฟ้า",
    intania: "106",
    daysAgo: 31,
    recommended: true,
    position: "Research Intern",
    duration: "3 เดือน",
    compensation: "15,000 บาท/เดือน",
    workMode: "Onsite",
    openYears: "ทุกชั้นปี",
    minGpa: null,
    scores: { work: 4, social: 4, mentor: 4, experience: 4 },
    sections: {
      application: "สมัครผ่านอาจารย์แนะนำและยื่นเอกสารกับหน่วยวิจัย มีสัมภาษณ์กับหัวหน้าโครงการ",
      work: "ได้ร่วมงานวิจัยและพัฒนาต้นแบบอุปกรณ์จริง ได้ฝึกเขียนรายงานเชิงวิชาการ",
      atmosphere: "บรรยากาศเหมือนงานวิจัยในมหาวิทยาลัย พี่ ๆ นักวิจัยใจดีและสอนละเอียด",
      advice: "เหมาะกับคนที่สนใจสายงานวิจัยหรือเรียนต่อปริญญาโท",
    },
  },
  {
    id: "ground-services-intern-thai-airways",
    companyId: "thai-airways",
    name: "Anonymous",
    department: "ภาคเครื่องกล",
    intania: "105",
    daysAgo: 45,
    recommended: false,
    position: "Ground Services Intern",
    duration: "2 เดือน",
    compensation: "12,000 บาท/เดือน",
    workMode: "Onsite",
    openYears: "ชั้นปีที่ 3-4",
    minGpa: 2.5,
    scores: { work: 3, social: 4, mentor: 3, experience: 3 },
    sections: {
      application: "สมัครผ่านเว็บไซต์บริษัท มีสัมภาษณ์รอบเดียว",
      work: "ได้เห็นกระบวนการซ่อมบำรุงเครื่องบินเบื้องต้น แต่ส่วนใหญ่เป็นการสังเกตการณ์มากกว่าลงมือทำ",
      atmosphere: "พี่ ๆ ใจดีแต่ระบบราชการค่อนข้างช้า",
      advice: "ถ้าอยากได้ประสบการณ์ hands-on เยอะ อาจต้องถามรายละเอียดงานก่อน",
    },
  },
  {
    id: "process-engineer-intern-boonrawd",
    companyId: "boonrawd-brewery",
    name: "Anonymous",
    department: "ภาคเคมี",
    intania: "107",
    daysAgo: 13,
    recommended: true,
    position: "Process Engineer Intern",
    duration: "2 เดือน",
    compensation: "14,000 บาท/เดือน",
    workMode: "Onsite",
    openYears: "ชั้นปีที่ 3-4",
    minGpa: 2.5,
    scores: { work: 4, social: 4, mentor: 4, experience: 4 },
    sections: {
      application: "สมัครผ่านเว็บไซต์บริษัท มีสัมภาษณ์ 1 รอบ",
      work: "ได้ลงโรงงานจริงและช่วยวิเคราะห์กระบวนการผลิตเครื่องดื่ม",
      atmosphere: "พี่ ๆ เป็นกันเอง บรรยากาศแบบโรงงานครอบครัวไทย",
      advice: "เตรียมพื้นฐานวิศวกรรมเคมีหรืออุตสาหการไปบ้างจะช่วยให้เข้าใจงานเร็วขึ้น",
    },
  },
  {
    id: "leasing-intern-central-pattana",
    companyId: "central-pattana",
    name: "Anonymous",
    department: "ภาคอุตสาหการ",
    intania: "108",
    daysAgo: 17,
    recommended: true,
    position: "Business Development Intern",
    duration: "2 เดือน",
    compensation: "13,000 บาท/เดือน",
    workMode: "Onsite",
    openYears: "ทุกชั้นปี",
    minGpa: null,
    scores: { work: 4, social: 4, mentor: 4, experience: 4 },
    sections: {
      application: "สมัครผ่านเว็บไซต์บริษัท มีสัมภาษณ์รอบเดียว",
      work: "ได้ช่วยวิเคราะห์ข้อมูลร้านค้าในศูนย์การค้าและเสนอไอเดียปรับปรุงพื้นที่เช่า",
      atmosphere: "ทีมเป็นมิตร บรรยากาศทำงานสบาย ๆ",
      advice: "เตรียมทักษะการวิเคราะห์ข้อมูลและนำเสนอไปด้วยจะช่วยได้มาก",
    },
  },
  {
    id: "merchandising-intern-bigc",
    companyId: "big-c",
    name: "Anonymous",
    department: "ภาคอุตสาหการ",
    intania: "106",
    daysAgo: 42,
    recommended: false,
    position: "Merchandising Intern",
    duration: "2 เดือน",
    compensation: "12,000 บาท/เดือน",
    workMode: "Onsite",
    openYears: "ทุกชั้นปี",
    minGpa: null,
    scores: { work: 3, social: 3, mentor: 3, experience: 3 },
    sections: {
      application: "สมัครผ่านเว็บไซต์บริษัท มีสัมภาษณ์รอบเดียว",
      work: "งานส่วนใหญ่เป็นการจัดเรียงข้อมูลสินค้าและช่วยงานเอกสาร ไม่ค่อยได้ใช้ความรู้เฉพาะทาง",
      atmosphere: "พี่ ๆ ใจดีแต่งานค่อนข้างซ้ำซาก",
      advice: "เหมาะกับคนที่อยากลองงานสาย retail แบบพื้นฐานก่อน",
    },
  },
  {
    id: "supply-chain-intern-unilever",
    companyId: "unilever-thailand",
    name: "Anonymous",
    department: "ภาคอุตสาหการ",
    intania: "107",
    daysAgo: 11,
    recommended: true,
    position: "Supply Chain Intern",
    duration: "3 เดือน",
    compensation: "18,000 บาท/เดือน",
    workMode: "Hybrid",
    openYears: "ชั้นปีที่ 3-4",
    minGpa: 2.75,
    scores: { work: 4, social: 4, mentor: 4, experience: 5 },
    sections: {
      application: "สมัครผ่านเว็บไซต์บริษัท มี online assessment และสัมภาษณ์ 2 รอบ",
      work: "ได้ร่วมโปรเจกต์ปรับปรุงประสิทธิภาพ supply chain และนำเสนอผลให้ผู้บริหารฟัง",
      atmosphere: "องค์กรอินเตอร์ วัฒนธรรมเปิดกว้าง พี่ ๆ ให้โอกาสได้ลองเยอะ",
      advice: "เตรียมภาษาอังกฤษให้พร้อม เพราะต้องสื่อสารกับทีมต่างประเทศบ่อย",
    },
  },
];

export const departments = Array.from(new Set(reviews.map((review) => review.department))).sort();

export const intaniaBatches = Array.from(new Set(reviews.map((review) => review.intania))).sort();
